spring.application.name=habit-tracker

#PostgreSQL configs - I use PostgreSQL for local system testing
#I am looking forward for cloud based ones, so that I can use it remotely

spring.datasource.url = jdbc:postgresql://localhost:5432/demo
spring.datasource.username = postgres
spring.datasource.password = dwarageshdc
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jp.show=sql = true
